spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scaler_security
    username: root
    password: MyNewPass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect